---
title: "Greens call for wolves to be reintroduced to Ireland"
description: |
  A short description of the post.
author:
  - name: Laurane Marcq
    url: {}
date: 10-15-2019
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Title of the article  

Greens call for wolves to be reintroduced to Ireland

## Name of the magazine and source 

The Irish Times, <https://www.irishtimes.com/news/politics/greens-call-for-wolves-to-be-reintroduced-to-ireland-1.4036692>

## Vocabulary 

| Words from the text | Synonym/explanation in English |
| ------------------- | ------------------------------ |
| Woodlands           | Forest            |
| Coniferous          | Type of tree   |
| Deciduous           | Other type of tree |
| To stop             | To see |
| To promote          | To boost |
| A deer              | Hoofed ruminant mammal |
| Herds               | A large number of animals |
| To undermine        | To waste |
| Plots               | Fields | 
| A canopy            | The branches and leaves that spread out at the top of a group of trees forming a type of roof |
| Commisionning       | The action of to control
| A flood             | To cause to fill or become covered with water |
## Analysis table 

|                              |                                                                     |
| ---------------------------- | ------------------------------------------------------------------- |
| Researchers                  | Harry McGee. He is a political correspondent with the Irish Times.                        |
| Published in?                | Wed, Oct 16, 2019                                                       |
| General topic?               |  (summarize the topic in one or two sentences)                      |
| Procedure/what was examined? | (Give some details about the topic, i.e. methodology/material/etc.) |
| Conclusions/discovery?       | The topic is a source of conflicts between Green Party leader Eamon Ryan and the Minister for Arts. So, no decision has been taken.    |
| Remaining questions?         | We don't know if wolves will be reintroduce in Ireland after 250 years without presence in this country. |


